fix: gha

diff --git a/.github/workflows/deploy_to_wakaba.yaml b/.github/workflows/deploy_to_wakaba.yaml
--- a/.github/workflows/deploy_to_wakaba.yaml
+++ b/.github/workflows/deploy_to_wakaba.yaml
@@ -2,7 +2,7 @@ name: Deploy to wakaba
 
 on:
   push:
-    branches: [main]
+    branches: [ main ]
   workflow_dispatch:
 
 concurrency:
@@ -138,7 +138,28 @@ jobs:
             --query "Command.CommandId" \
             --output text)
 
-          sleep 5  # コマンドが実行されるまで待つ
-          aws ssm list-command-invocations --command-id "$COMMAND_ID" --details
+          RETRY_COUNT=0
+          while true; do
+            # コマンドのステータスを取得し、失敗や成功、進行中の状態を確認
+            STATUS=$(aws ssm list-command-invocations --command-id "$COMMAND_ID" --query "CommandInvocations[0].Status" --output text)
 
-          INVOCATIONS=$(aws ssm list-command-invocations --command-id "$COMMAND_ID" --details)
+            if [ "$STATUS" = "Success" ]; then
+              echo "Success to deploy"
+              break
+            elif [ "$STATUS" = "Failed" ]; then
+              echo "Failed to deploy"
+              aws ssm list-command-invocations --command-id "$COMMAND_ID" --details
+              exit 1
+            elif [ "$STATUS" = "InProgress" ]; then
+              if [ "$RETRY_COUNT" -ge "$RETRY_LIMIT" ]; then
+                echo "Retry limit exceeded"
+                exit 1
+              fi
+              echo "Retry after 1 second (retry count: $RETRY_COUNT)"
+              RETRY_COUNT=$((RETRY_COUNT + 1))
+              sleep 1
+            else
+              echo "Unknown status: $STATUS"
+              exit 1
+            fi
+          done
